### ISSUE TITLE
"mem connect" issue

### ISSUE THREAD

**Issue by yanivbh1** [Memphis-OS/memphis-cli#45]
Hey,
I tried the following, nothing works - 
<img width="478" alt="Screen Shot 2022-04-30 at 17 57 49" src="https://user-images.githubusercontent.com/70286779/166110752-9ce42387-b0b1-42f5-92e5-d5e4ed960968.png">

**Comment by shay23b** [comment]
Hi, 
Please connect without 'api' at the end, nothing should appear at the end of the URL
