### ISSUE TITLE
Wrong display of path in "mem init"

### ISSUE THREAD

**Issue by yanivbh1** [Memphis-OS/memphis-cli#46]

**Comment by yanivbh1** [comment]
'mem init' creates an example project for connecting an app with Memphis.

The default language is nodejs.
If you want to use different language use 'mem init -l/--language <language>'.
Currently supported languages: nodejs.

For more help use 'mem init -h'.

The project will be created in directory **/snapshot/memphis-cli/actions**
 continue? Y/ny

It creates it in the location of my terminal, which is ok, but show me a different location in the prompt

**Comment by shay23b** [comment]
Fixed in v0.1.2
