### ISSUE TITLE
location of .memconfig is wrong

### ISSUE THREAD

**Issue by yanivbh1** [Memphis-OS/memphis-cli#65]
Hey,
The location of .memconfig at creation time should be constant, based on the OS of the user,
similar to .kubeconfig or .awscli.

**AWS CLI config file for example -** 

Operating system | Default location of files
-- | --
Linux and macOS | ~/.aws/config ~/.aws/credentials
Windows | %USERPROFILE%\.aws\config %USERPROFILE%\.aws\credentials

If we save it where the terminal is currently at, in my use case it was inside a code repo, the user would then need to add it to .gitignore

**Comment by shay23b** [comment]
solved in v0.2.1
