### ISSUE TITLE
Username parameter alignment 

### ISSUE THREAD

**Issue by valeraBr** [Memphis-OS/memphis-cli#80]
Username parameter is not the same in section "Connect" and "User".

When you try to connect to control plane you need to use "-u, --user" for username, and in the "User" section its "-n, --name <user-name> ".

Example:
Connect:
$ mem connect -u root -p memphis -s http://localhost:5555
User:
$ mem user add --name shay --password 123456

In my opinion "-u, --user" is more intuitive and user-friendly option.

**Comment by idanasulinmemphis** [comment]
released on 0.2.8 version
